config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/about'

  get 'static_pages/contact'

  resources :user_notes
  resources :users

  root 'user_notes#main'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'new_user' => 'users#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_notes
  has_secure_password
  
end

app/models/user_note.rb
class UserNote < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def index
    render text: "TODO"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/user_notes_controller.rb
class UserNotesController < ApplicationController
  before_action :set_user_note, only: [:show, :edit, :update, :destroy]

  # GET /user_notes
  # GET /user_notes.json
  def index
    @user_notes = UserNote.all
  end
  
  def main
    @user_notes = UserNote.all
    @user_note  = UserNote.new
    @user_list = User.all
  end

  # GET /user_notes/1
  # GET /user_notes/1.json
  def show
  end

  # GET /user_notes/new
  def new
    @user_note = UserNote.new
  end

  # GET /user_notes/1/edit
  def edit
  end

  # POST /user_notes
  # POST /user_notes.json
  def create
    @user_note = UserNote.new(user_note_params)

    respond_to do |format|
      if @user_note.save
        format.html { redirect_to @user_note, notice: 'User note was successfully created.' }
        format.json { render :show, status: :created, location: @user_note }
      else
        format.html { render :new }
        format.json { render json: @user_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_notes/1
  # PATCH/PUT /user_notes/1.json
  def update
    respond_to do |format|
      if @user_note.update(user_note_params)
        format.html { redirect_to @user_note, notice: 'User note was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_note }
      else
        format.html { render :edit }
        format.json { render json: @user_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_notes/1
  # DELETE /user_notes/1.json
  def destroy
    @user_note.destroy
    respond_to do |format|
      format.html { redirect_to user_notes_url, notice: 'User note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_note
      @user_note = UserNote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_note_params
      params.require(:user_note).permit(:note, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end
  
  # GET /users/signup
  def signup
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_notes_helper.rb
module UserNotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleWebApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<!-- % if cUser != nil %> -->
  <div align="right"><h2>Welcome, UserName</h2></div>
  
<!-- % else %> -->
  <div align="right"><h2>You are not signed in. Login or Sign Up Now!</h2></div>

<!-- % end %> -->
  

<!-- or -->

<hr>

<%= yield %>


<hr>
<div align="right">
  <%= link_to "Home", root_path %>
  <%= link_to "About", about_path %>  
  <%= link_to "Contact", contact_path %>
  <%= link_to "Create User", new_user_path %>
</div>

</body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/user_notes/_form.html.erb
<%= form_for(@user_note) do |f| %>
  <% if @user_note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_note.errors.count, "error") %> prohibited this user_note from being saved:</h2>

      <ul>
      <% @user_note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_notes/edit.html.erb
<h1>Editing User Note</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_note %> |
<%= link_to 'Back', user_notes_path %>

app/views/user_notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Notes</h1>

<table>
  <thead>
    <tr>
      <th>Note</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_notes.each do |user_note| %>
      <tr>
        <td><%= user_note.note %></td>
        <td><%= user_note.user_id %></td>
        <td><%= link_to 'Show', user_note %></td>
        <td><%= link_to 'Edit', edit_user_note_path(user_note) %></td>
        <td><%= link_to 'Destroy', user_note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User note', new_user_note_path %>

app/views/user_notes/main.html.erb
<p id="notice"><%= notice %></p>


<%= render 'form' %>

<table>
  <thead>
    <tr>
      <th>Note</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<!-- TODO retrieve user name based on id -->
  <tbody>
    <% @user_notes.each do |user_note| %>
      <tr>
        <td><%= user_note.note %></td>
        <td><%= (User.find(user_note.user_id)).username %></td>
        <!-- user_list.find(user_note.user_id)  does not work -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/user_notes/new.html.erb
<h1>New User Note</h1>

<%= render 'form' %>

<%= link_to 'Back', user_notes_path %>

app/views/user_notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Note:</strong>
  <%= @user_note.note %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_note.user_id %>
</p>

<%= link_to 'Edit', edit_user_note_path(@user_note) %> |
<%= link_to 'Back', user_notes_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/signup.html.erb
<h1>New User</h1>